---
name: cmpsc-312-Spring-2022-lab4
break: true
indent: 4
---

# --> check the technical writing
writing/report.md:
    ConfirmFileExists
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    MatchFileFragment --fragment "Add Your Account Name Here" --count 0 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact

src/myDB_builder.txt:
    ConfirmFileExists
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    MatchFileFragment --fragment "Add Your Account Name Here" --count 0 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact


# --> check the number of commits beyond a threshold
CountCommits --count 3
